apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: prometheus-global
  {{- if .Values.vice_president }}
  annotations:
    vice-president: "true"
  {{- end}}

spec:
  tls:
     - secretName: prometheus-global
       hosts: [{{ required ".Values.ingress.host undefined" .Values.ingress.host }}.{{ required ".Values.ingress.subdomain undefined" .Values.ingress.subdomain }}.{{ required ".Values.global.domain undefined" .Values.global.domain }}]
  rules:
    - host: {{ required ".Values.ingress.host undefined" .Values.ingress.host }}.{{ required ".Values.ingress.subdomain undefined" .Values.ingress.subdomain }}.{{ required ".Values.global.domain undefined" .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: prometheus-global
            servicePort: 9090
